# Generated by Django 6.0.7 on 2026-08-12 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_rename_vehiclie_type_courierprofile_vehicle_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='firm',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'FIRM'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='couriers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('COURIER', 'Courier'), ('FIRM', 'Firm')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='courierprofile',
            index=models.Index(fields=['firm'], name='users_couri_firm_id_99f4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='courierprofile',
            index=models.Index(fields=['current_status'], name='users_couri_current_066fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='firmprofile',
            index=models.Index(fields=['firm_type'], name='users_firmp_firm_ty_a35d90_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='users_user_is_veri_9ce429_idx'),
        ),
    ]
