# Generated by Django 6.0.7 on 2026-08-12 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_todo'),
        ('users', '0002_rename_vehiclie_type_courierprofile_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='firm',
            field=models.ForeignKey(blank=True, help_text='Firm this task belongs to. Auto-set when the assigner is a FIRM.', limit_choices_to={'role': 'FIRM'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'FIRM'}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_position',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='todo',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_order_status_2f1723_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier', 'status'], name='order_order_courier_10880a_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['courier', 'status'], name='order_todo_courier_260054_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['firm'], name='order_todo_firm_id_f3c824_idx'),
        ),
    ]
